version: '3'

services:

  website:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - ./src:/opt/scfair-test:cached
      - ./data:/data/scfair-test/
    env_file: .env.test
    environment:
      - RAILS_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
      solr:
        condition: service_healthy
    networks:
      - scfair_network
    restart: always

  postgres:
    image: postgres:15.4
    env_file: .env.test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - scfair_network
    restart: always

  solr:
    build:
      context: ./src/solr
      dockerfile: Dockerfile
    image: scfair-solr:latest
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command: solr-precreate production /opt/solr/server/solr/configsets/sunspot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      SOLR_HEAP: 2g
      SOLR_JAVA_MEM: -Xms512m -Xmx2g
    networks:
      - scfair_network
    restart: always

networks:
  scfair_network:
    driver: bridge

volumes:
  postgres-data:
  solr_data:
    driver: local
  solr_logs:
