ext_sources = [
  {
    url_mask: "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=#ID",
    name: "GEO series",
    description: "GEO series",
    id_regexp: "^GSE\\d+$"
  },
  {
    url_mask: "https://www.protocols.io/view/#ID",
    name: "protocols.io",
    description: "Protocols",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://cellxgene.cziscience.com/collections/#ID",
    name: "CELLxGENE collection",
    description: "CELLxGENE collection",
    id_regexp: "^[\\d\\w\\-]+$"
  },
  {
    url_mask: "https://explore.data.humancellatlas.org/projects/#ID https://data.humancellatlas.org/explore/projects/#ID",
    name: "HumanCellAtlas",
    description: "HumanCellAtlas",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://hubmapconsortium.org/",
    name: "HubMap consortium",
    description: "HubMap consortium"
  },
  {
    url_mask: "https://atlas.kpmp.org/explorer",
    name: "KPMP atlas",
    description: "KPMP atlas"
  },
  {
    url_mask: "https://www.kpmp.org/",
    name: "KPMP website",
    description: "KPMP website"
  },
  {
    url_mask: "https://actagingresearch.org/",
    name: "Adult Changes in Thought Study",
    description: "Adult Changes in Thought Study"
  },
  {
    url_mask: "https://adknowledgeportal.synapse.org/Explore/Studies/DetailsPage/StudyData?Study=#ID",
    name: "AD knowledge portal",
    description: "AD knowledge portal",
    id_regexp: "^syn\\d+$"
  },
  {
    url_mask: "http://depts.washington.edu/mbwc/adrc",
    name: "Alzheimer's Disease Research Center",
    description: "Alzheimer's Disease Research Center"
  },
  {
    url_mask: "https://dlmp.uw.edu/research-labs/keene/BRaIN-lab",
    name: "BRaIN-lab",
    description: "BRaIN-lab"
  },
  {
    url_mask: "https://portal.brain-map.org/explore/#ID",
    name: "Allen Brain Map",
    description: "Allen Brain Map",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://registry.opendata.aws/#ID",
    name: "AWS Open Data",
    description: "Registry of Open Data on AWS",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://www.synapse.org/#ID",
    name: "synapse.org",
    description: "synapse.org",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://github.com/#ID http://www.github.com/#ID",
    name: "Github",
    description: "Github",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://www.ebi.ac.uk/biostudies/arrayexpress/studies/#ID https://www.ebi.ac.uk/arrayexpress/experiments/#ID",
    name: "ArrayExpress BioStudies",
    description: "ArrayExpress BioStudies",
    id_regexp: "^E-MTAB-\\d+$"
  },
  {
    url_mask: "https://assets.nemoarchive.org/#ID http://data.nemoarchive.org/#ID",
    name: "NeMo archive",
    description: "The Neuroscience Multi-omic Data Archive",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://portal.brain-map.org/atlases-and-data/#ID",
    name: "Allen Brain Map Atlases",
    description: "Allen Brain Map Atlases",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://hq-1.gitbook.io/mc",
    name: "YAP",
    description: "YAP"
  },
  {
    url_mask: "http://neomorph.salk.edu/mouse_brain.php",
    name: "Mouse CEMBA Brain",
    description: "Mouse CEMBA Brain"
  },
  {
    url_mask: "http://neomorph.salk.edu/omb/",
    name: "Brain Cell Methylation Viewer",
    description: "Brain Cell Methylation Viewer"
  },
  {
    url_mask: "https://osf.io/rac5w/",
    name: "OSFHome Single Cell CHIP",
    description: "OSFHome Single Cell CHIP"
  },
  {
    url_mask: "https://www.ebi.ac.uk/biostudies/bioimages/studies/#ID",
    name: "Bioimage Archive",
    description: "Bioimage Archive",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://cells.ucsc.edu/?ds=#ID http://cells.ucsc.edu/?ds=#ID https://#ID.cells.ucsc.edu/",
    name: "UCSC Cell Browser",
    description: "UCSC Cell Browser",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://#ID.ds.czbiohub.org/",
    name: "CZ BioHub Portal",
    description: "CZ BioHub Portal",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://#ID.cellgeni.sanger.ac.uk/",
    name: "Sanger Dataset",
    description: "Sanger Dataset",
    id_regexp: "^.+?"
  },
  {
    url_mask: "https://www.hubrecht.eu/research-groups/van-oudenaarden-group/",
    name: "van Oudenaarden lab",
    description: "van Oudenaarden lab"
  },
  {
    url_mask: "https://ega-archive.org/datasets/#ID",
    name: "EGA dataset",
    description: "European Genome-Phenome Archive Dataset",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://ega-archive.org/studies/#ID",
    name: "EGA Study",
    description: "European Genome-Phenome Archive Study",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=#ID",
    name: "dbGaP Study",
    description: "dbGAP Study",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://genome.ucsc.edu/cgi-bin/#ID",
    name: "UCSC Genome Browser",
    description: "UCSC Genome Browser",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "http://humphreyslab.com/SingleCell/",
    name: "Kidney Online Transcriptomics",
    description: "Kidney Online Transcriptomics"
  },
  {
    url_mask: "https://zenodo.org/records/#ID https://zenodo.org/record/#ID",
    name: "Zenodo record",
    description: "Zenodo record",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://www.niaid.nih.gov/research/john-tsang-phd",
    name: "John Tsang group",
    description: "John Tsang group"
  },
  {
    url_mask: "https://www.ebi.ac.uk/gxa/sc/experiments/#ID",
    name: "Single Cell Expression Atlas Experiment",
    description: "Single Cell Expression Atlas Experiment",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://www.cellphonedb.org/ http://www.cellphonedb.org/",
    name: "CellphoneDB",
    description: "CellphoneDB"
  },
  {
    url_mask: "https://www.gutcellatlas.org",
    name: "Gut Cell Survey",
    description: "Gut Cell Survey"
  },
  {
    url_mask: "https://developmental.cellatlas.io/#ID",
    name: "Human Cell Atlas Developmental",
    description: "Human Cell Atlas Developmental",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://singlecell.broadinstitute.org/single_cell/study/#ID",
    name: "BroadInstitute Single-Cell Portal",
    description: "BroadInstitute Single-Cell Portal",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "http://www.teichlab.org/",
    name: "Teichmann lab",
    description: "Teichmann lab"
  },
  {
    url_mask: "https://www.kramannlab.com/",
    name: "Kramann lab",
    description: "Kramann lab"
  },
  {
    url_mask: "https://www.sanger.ac.uk/project/#ID",
    name: "Sanger Institute Project",
    description: "Sanger Institute Project",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "http://www.breastatlas.org/ https://navinlabcode.github.io/HumanBreastCellAtlas.github.io/",
    name: "The Human Breast Cell Atlas",
    description: "The Human Breast Cell Atlas"
  },
  {
    url_mask: "https://figshare.com/articles/dataset/#ID",
    name: "FigShare Dataset",
    description: "FigShare Dataset",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://www.insitubiology.org/",
    name: "Chen Lab",
    description: "Chen Lab"
  },
  {
    url_mask: "https://data.mendeley.com/datasets/#ID",
    name: "Mendeley Data Dataset",
    description: "Mendeley Data Dataset",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://www.covid19cellatlas.org/index.patient.html",
    name: "COVID-19 cell atlas",
    description: "COVID-19 cell atlas"
  },
  {
    url_mask: "https://toliaslab.org/",
    name: "Andreas Tolias lab",
    description: "Andreas Tolias lab"
  },
  {
    url_mask: "https://apps.embl.de/abseqapp/",
    name: "ABseq App",
    description: "A resource of gene and surface protein expression in human bone marrow"
  },
  {
    url_mask: "https://git.embl.de/#ID",
    name: "EMBL GitLab",
    description: "EMBL GitLab",
    id_regexp: "^.+?$"
  },
  {
    url_mask: "https://www.ncbi.nlm.nih.gov/sra/#ID",
    name: "SRA Project",
    description: "SRA Project",
    id_regexp: "^SRP.+?$"
  },
  {
    url_mask: "https://www.ebi.ac.uk/ena/browser/view/#ID",
    name: "ENA Project",
    description: "European Nucleotide Archive",
    id_regexp: "^ERP|PRJEB.+?$"
  },
  {
    url_mask: "https://omg.gs.washington.edu/",
    name: "Ontogeny of Mouse, Graphed",
    description: "Ontogeny of Mouse, Graphed"
  },
  {
    url_mask: "http://dx.doi.org/#ID https://doi.org/#ID",
    name: "DOI",
    description: "DOI",
    id_regexp: "^.+?$"
  }
]

ext_sources.each do |source|
  ExtSource.find_or_create_by!(name: source[:name]) do |es|
    es.url_mask = source[:url_mask]
    es.description = source[:description]
    es.id_regexp = source[:id_regexp]
  end
end

Organism.create!([
  { external_reference_id: 185, name: "Apteryx haastii", short_name: "Great spotted kiwi", tax_id: 8823 },
  { external_reference_id: 176, name: "Apteryx owenii", short_name: "Little spotted kiwi", tax_id: 8824 },
  { external_reference_id: 186, name: "Apteryx rowi", short_name: "Okarito brown kiwi", tax_id: 308060 },
  { external_reference_id: 194, name: "Bison bison bison", short_name: "American bison", tax_id: 43346 },
  { external_reference_id: 192, name: "Bos mutus", short_name: "Wild yak", tax_id: 72004 },
  { external_reference_id: 187, name: "Calidris pugnax", short_name: "Ruff", tax_id: 198806 },
  { external_reference_id: 171, name: "Calidris pygmaea", short_name: "Spoon-billed sandpiper", tax_id: 425635 },
  { external_reference_id: 207, name: "Castor canadensis", short_name: "American beaver", tax_id: 51338 },
  { external_reference_id: 181, name: "Chelonoidis abingdonii", short_name: "Abingdon island giant tortoise", tax_id: 106734 },
  { external_reference_id: 199, name: "Coturnix japonica", short_name: "Japanese quail", tax_id: 93934 },
  { external_reference_id: 116, name: "Cricetulus griseus chok1gshd", short_name: "Chinese hamster CHOK1GS", tax_id: 10029 },
  { external_reference_id: 202, name: "Cricetulus griseus picr", short_name: "Chinese hamster PICR", tax_id: 10029 },
  { external_reference_id: 206, name: "Crocodylus porosus", short_name: "Australian saltwater crocodile", tax_id: 8502 },
  { external_reference_id: 196, name: "Cyanistes caeruleus", short_name: "Blue tit", tax_id: 156563 },
  { external_reference_id: 152, name: "Cyprinodon variegatus", short_name: "Sheepshead minnow", tax_id: 28743 },
  { external_reference_id: 175, name: "Dromaius novaehollandiae", short_name: "Emu", tax_id: 8790 },
  { external_reference_id: 72, name: "Gopherus agassizii", short_name: "Agassiz's desert tortoise", tax_id: 38772 },
  { external_reference_id: 122, name: "Heterocephalus glaber male", short_name: "Naked mole-rat male", tax_id: 10181 },
  { external_reference_id: 1, name: "Homo sapiens", short_name: "human", tax_id: 9606 },
  { external_reference_id: 191, name: "Junco hyemalis", short_name: "Dark-eyed junco", tax_id: 40217 },
  { external_reference_id: 177, name: "Lepidothrix coronata", short_name: "Blue-crowned manakin", tax_id: 321398 },
  { external_reference_id: 183, name: "Lonchura striata domestica", short_name: "Bengalese finch", tax_id: 299123 },
  { external_reference_id: 188, name: "Manacus vitellinus", short_name: "Golden-collared manakin", tax_id: 328815 },
  { external_reference_id: 189, name: "Marmota marmota marmota", short_name: "Alpine marmot", tax_id: 9994 },
  { external_reference_id: 182, name: "Melopsittacus undulatus", short_name: "Budgerigar (Pre)", tax_id: 13146 },
  { external_reference_id: 190, name: "Meriones unguiculatus", short_name: "Mongolian gerbil", tax_id: 10047 },
  { external_reference_id: 99, name: "Mus musculus balbcj", short_name: "Mouse BALB/cJ", tax_id: 10090 },
  { external_reference_id: 105, name: "Mus musculus c57bl6nj", short_name: "Mouse C57BL/6NJ", tax_id: 10090 },
  { external_reference_id: 98, name: "Mus musculus fvbnj", short_name: "Mouse FVB/NJ", tax_id: 10090 },
  { external_reference_id: 76, name: "Mus musculus nodshiltj", short_name: "Mouse NOD/ShiLtJ", tax_id: 10090 },
  { external_reference_id: 101, name: "Mus musculus nzohlltj", short_name: "Mouse NZO/HlLtJ", tax_id: 10090 },
  { external_reference_id: 106, name: "Mus musculus wsbeij", short_name: "Mouse WSB/EiJ", tax_id: 10092 },
  { external_reference_id: 203, name: "Mus spicilegus", short_name: "Steppe mouse", tax_id: 10103 },
  { external_reference_id: 29, name: "Myotis lucifugus", short_name: "little brown bat", tax_id: 59463 },
  { external_reference_id: 178, name: "Neovison vison", short_name: "American mink", tax_id: 452646 },
  { external_reference_id: 111, name: "Notamacropus eugenii", short_name: "Wallaby", tax_id: 9315 },
  { external_reference_id: 193, name: "Notechis scutatus", short_name: "Mainland tiger snake", tax_id: 8663 },
  { external_reference_id: 172, name: "Nothoprocta perdicaria", short_name: "Chilean tinamou", tax_id: 30464 },
  { external_reference_id: 184, name: "Numida meleagris", short_name: "Helmeted guineafowl", tax_id: 8996 },
  { external_reference_id: 198, name: "Parus major", short_name: "Great Tit", tax_id: 9157 },
  { external_reference_id: 204, name: "Piliocolobus tephrosceles", short_name: "Ugandan red Colobus", tax_id: 591936 },
  { external_reference_id: 170, name: "Pogona vitticeps", short_name: "Central bearded dragon", tax_id: 103695 },
  { external_reference_id: 200, name: "Prolemur simus", short_name: "Greater bamboo lemur", tax_id: 1328070 },
  { external_reference_id: 173, name: "Salvator merianae", short_name: "Argentine black and white tegu", tax_id: 96440 },
  { external_reference_id: 195, name: "Serinus canaria", short_name: "Common canary", tax_id: 9135 },
  { external_reference_id: 77, name: "Seriola lalandi dorsalis", short_name: "Yellowtail amberjack", tax_id: 1841481 },
  { external_reference_id: 174, name: "Spermophilus dauricus", short_name: "Daurian ground squirrel", tax_id: 99837 },
  { external_reference_id: 197, name: "Theropithecus gelada", short_name: "Gelada", tax_id: 9565 },
  { external_reference_id: 205, name: "Urocitellus parryii", short_name: "Arctic ground squirrel", tax_id: 9999 },
  { external_reference_id: 201, name: "Zonotrichia albicollis", short_name: "White-throated sparrow", tax_id: 44394 },
  { external_reference_id: 225, name: "Aspergillus terreus", short_name: "Aspergillus terreus NIH2624", tax_id: 341663 },
  { external_reference_id: 180, name: "Anser brachyrhynchus", short_name: "Pink-footed goose", tax_id: 132585 },
  { external_reference_id: 283, name: "Fusarium fujikuroi", short_name: "Fusarium fujikuroi", tax_id: 5127 },
  { external_reference_id: 315, name: "Zymoseptoria tritici", short_name: "Zymoseptoria tritici", tax_id: 336722 },
  { external_reference_id: 229, name: "Caenorhabditis brenneri", short_name: "Caenorhabditis brenneri", tax_id: 135651 },
  { external_reference_id: 231, name: "Caenorhabditis japonica", short_name: "Caenorhabditis japonica", tax_id: 281687 },
  { external_reference_id: 272, name: "Aspergillus fumigatusa1163", short_name: "Aspergillus fumigatus A1163", tax_id: 451804 },
  { external_reference_id: 14, name: "Anas platyrhynchos", short_name: "mallard", tax_id: 8839 },
  { external_reference_id: 20, name: "Danio rerio", short_name: "zebrafish", tax_id: 7955 },
  { external_reference_id: 9, name: "Equus caballus", short_name: "horse", tax_id: 9796 },
  { external_reference_id: 6, name: "Ficedula albicollis", short_name: "collared flycatcher", tax_id: 59894 },
  { external_reference_id: 13, name: "Gadus morhua", short_name: "Atlantic cod", tax_id: 8049 },
  { external_reference_id: 42, name: "Gorilla gorilla", short_name: "western gorilla", tax_id: 9593 },
  { external_reference_id: 60, name: "Macaca mulatta", short_name: "Rhesus monkey", tax_id: 9544 },
  { external_reference_id: 58, name: "Nomascus leucogenys", short_name: "northern white-cheeked gibbon", tax_id: 61853 },
  { external_reference_id: 32, name: "Ornithorhynchus anatinus", short_name: "platypus", tax_id: 9258 },
  { external_reference_id: 7, name: "Sarcophilus harrisii", short_name: "Tasmanian devil", tax_id: 9305 },
  { external_reference_id: 11, name: "Sus scrofa", short_name: "pig", tax_id: 9823 },
  { external_reference_id: 45, name: "Takifugu rubripes", short_name: "torafugu", tax_id: 31033 },
  { external_reference_id: 274, name: "Blumeria graminis", short_name: "Blumeria graminis", tax_id: 546991 },
  { external_reference_id: 54, name: "Chlorocebus sabaeus", short_name: "green monkey", tax_id: 60711 },
  { external_reference_id: 276, name: "Colletotrichum gloeosporioides", short_name: "Colletotrichum gloeosporioides", tax_id: 1213859 },
  { external_reference_id: 277, name: "Colletotrichum graminicola", short_name: "Colletotrichum graminicola", tax_id: 645133 },
  { external_reference_id: 278, name: "Colletotrichum higginsianum", short_name: "Colletotrichum higginsianum", tax_id: 80884 },
  { external_reference_id: 279, name: "Colletotrichum orbiculare", short_name: "Colletotrichum orbiculare", tax_id: 1213857 },
  { external_reference_id: 281, name: "Dothistroma septosporum", short_name: "Dothistroma septosporum", tax_id: 675120 },
  { external_reference_id: 282, name: "Fusarium culmorum", short_name: "Fusarium culmorum UK99", tax_id: 1318462 },
  { external_reference_id: 284, name: "Fusarium graminearum", short_name: "Fusarium graminearum str. PH-1", tax_id: 5518 },
  { external_reference_id: 285, name: "Fusarium oxysporum", short_name: "Fusarium oxysporum", tax_id: 426428 },
  { external_reference_id: 287, name: "Fusarium solani", short_name: "Fusarium solani", tax_id: 660122 },
  { external_reference_id: 288, name: "Fusarium verticillioides", short_name: "Fusarium verticillioides", tax_id: 334819 },
  { external_reference_id: 289, name: "Gaeumannomyces graminis", short_name: "Gaeumannomyces tritici R3-111a-1", tax_id: 644352 },
  { external_reference_id: 290, name: "Komagataella pastoris", short_name: "Komagataella pastoris", tax_id: 644223 },
  { external_reference_id: 293, name: "Magnaporthe poae", short_name: "Magnaporthe poae", tax_id: 644358 },
  { external_reference_id: 295, name: "Microbotryum violaceum", short_name: "Microbotryum violaceum", tax_id: 683840 },
  { external_reference_id: 297, name: "Puccinia graminis", short_name: "Puccinia graminis", tax_id: 418459 },
  { external_reference_id: 298, name: "Puccinia graminisug99", short_name: "Puccinia graminis Ug99", tax_id: 1040990 },
  { external_reference_id: 300, name: "Puccinia triticina", short_name: "Puccinia triticina", tax_id: 630390 },
  { external_reference_id: 301, name: "Pyrenophora teres", short_name: "Pyrenophora teres", tax_id: 861557 },
  { external_reference_id: 305, name: "Schizosaccharomyces octosporus", short_name: "Schizosaccharomyces octosporus", tax_id: 483514 },
  { external_reference_id: 308, name: "Trichoderma reesei", short_name: "Trichoderma reesei", tax_id: 431241 },
  { external_reference_id: 309, name: "Trichoderma virens", short_name: "Trichoderma virens", tax_id: 413071 },
  { external_reference_id: 314, name: "Yarrowia lipolytica", short_name: "Yarrowia lipolytica", tax_id: 284591 },
  { external_reference_id: 317, name: "Adineta vaga", short_name: "Adineta vaga", tax_id: 104782 },
  { external_reference_id: 319, name: "Anopheles darlingi", short_name: "Anopheles darlingi", tax_id: 43151 },
  { external_reference_id: 320, name: "Anoplophora glabripennis", short_name: "Anoplophora glabripennis", tax_id: 217634 },
  { external_reference_id: 323, name: "Belgica antarctica", short_name: "Belgica antarctica", tax_id: 315563 },
  { external_reference_id: 324, name: "Bombus impatiens", short_name: "Bombus impatiens", tax_id: 132113 },
  { external_reference_id: 327, name: "Branchiostoma lanceolatum", short_name: "Branchiostoma lanceolatum", tax_id: 7740 },
  { external_reference_id: 337, name: "Folsomia candida", short_name: "Folsomia candida str. VU population", tax_id: 158441 },
  { external_reference_id: 341, name: "Leptotrombidium deliense", short_name: "Leptotrombidium deliense", tax_id: 299467 },
  { external_reference_id: 345, name: "Lucilia cuprina", short_name: "Lucilia cuprina", tax_id: 7375 },
  { external_reference_id: 346, name: "Mayetiola destructor", short_name: "Mayetiola destructor", tax_id: 39758 },
  { external_reference_id: 348, name: "Melitaea cinxia", short_name: "Melitaea cinxia", tax_id: 113334 },
  { external_reference_id: 349, name: "Mnemiopsis leidyi", short_name: "Mnemiopsis leidyi", tax_id: 27923 },
  { external_reference_id: 251, name: "Oryza indica", short_name: "Oryza sativa Indica Group", tax_id: 39946 },
  { external_reference_id: 439, name: "Plasmodium berghei", short_name: "Plasmodium berghei", tax_id: 5823 },
  { external_reference_id: 440, name: "Plasmodium chabaudi", short_name: "Plasmodium chabaudi", tax_id: 31271 },
  { external_reference_id: 258, name: "Plasmodium knowlesi", short_name: "Plasmodium knowlesi", tax_id: 5851 },
  { external_reference_id: 273, name: "Beauveria bassiana", short_name: "Beauveria bassiana", tax_id: 176275 },
  { external_reference_id: 83, name: "Cavia aperea", short_name: "Brazilian guinea pig", tax_id: 37548 },
  { external_reference_id: 59, name: "Cavia porcellus", short_name: "domestic guinea pig", tax_id: 10141 },
  { external_reference_id: 71, name: "Cercocebus atys", short_name: "Sooty mangabey", tax_id: 9531 },
  { external_reference_id: 133, name: "Colobus angolensis palliatus", short_name: "Angola colobus", tax_id: 336983 },
  { external_reference_id: 78, name: "Cynoglossus semilaevis", short_name: "Tongue sole", tax_id: 244447 },
  { external_reference_id: 24, name: "Dipodomys ordii", short_name: "Ord's kangaroo rat", tax_id: 10020 },
  { external_reference_id: 266, name: "Electrophorus electricus", short_name: "Electric eel", tax_id: 8005 },
  { external_reference_id: 136, name: "Eptatretus burgeri", short_name: "Hagfish", tax_id: 7764 },
  { external_reference_id: 165, name: "Equus asinus asinus", short_name: "Donkey", tax_id: 83772 },
  { external_reference_id: 143, name: "Esox lucius", short_name: "Northern pike", tax_id: 8010 },
  { external_reference_id: 150, name: "Fundulus heteroclitus", short_name: "Mummichog", tax_id: 8078 },
  { external_reference_id: 155, name: "Gambusia affinis", short_name: "Western mosquitofish", tax_id: 33528 },
  { external_reference_id: 81, name: "Hippocampus comes", short_name: "Tiger tail seahorse", tax_id: 109280 },
  { external_reference_id: 267, name: "Hucho hucho", short_name: "Huchen", tax_id: 62062 },
  { external_reference_id: 153, name: "Ictalurus punctatus", short_name: "Channel catfish", tax_id: 7998 },
  { external_reference_id: 142, name: "Labrus bergylta", short_name: "Ballan wrasse", tax_id: 56723 },
  { external_reference_id: 55, name: "Lepisosteus oculatus", short_name: "spotted gar", tax_id: 7918 },
  { external_reference_id: 154, name: "Mastacembelus armatus", short_name: "Zig-zag eel", tax_id: 205130 },
  { external_reference_id: 28, name: "Microcebus murinus", short_name: "gray mouse lemur", tax_id: 30608 },
  { external_reference_id: 157, name: "Mola mola", short_name: "Ocean sunfish", tax_id: 94237 },
  { external_reference_id: 84, name: "Mus musculus akrj", short_name: "Mouse AKR/J", tax_id: 10090 },
  { external_reference_id: 2, name: "Mus musculus", short_name: "mouse", tax_id: 10090 },
  { external_reference_id: 92, name: "Mus musculus dba2j", short_name: "Mouse DBA/2J", tax_id: 10090 },
  { external_reference_id: 119, name: "Mus pahari", short_name: "Shrew mouse", tax_id: 10093 },
  { external_reference_id: 134, name: "Mus spretus", short_name: "Algerian mouse", tax_id: 10096 },
  { external_reference_id: 19, name: "Ochotona princeps", short_name: "American pika", tax_id: 9978 },
  { external_reference_id: 57, name: "Oryzias latipes", short_name: "Japanese medaka", tax_id: 8090 },
  { external_reference_id: 138, name: "Oryzias latipes hni", short_name: "Japanese medaka HNI", tax_id: 8090 },
  { external_reference_id: 21, name: "Pan troglodytes", short_name: "chimpanzee", tax_id: 9598 },
  { external_reference_id: 70, name: "Panthera pardus", short_name: "Leopard", tax_id: 9691 },
  { external_reference_id: 10, name: "Papio anubis", short_name: "olive baboon", tax_id: 9555 },
  { external_reference_id: 74, name: "Phascolarctos cinereus", short_name: "Koala", tax_id: 38626 },
  { external_reference_id: 16, name: "Poecilia formosa", short_name: "Amazon molly", tax_id: 48698 },
  { external_reference_id: 31, name: "Procavia capensis", short_name: "Cape rock hyrax", tax_id: 9813 },
  { external_reference_id: 126, name: "Propithecus coquereli", short_name: "Coquerel's sifaka", tax_id: 379532 },
  { external_reference_id: 141, name: "Pundamilia nyererei", short_name: "Makobe Island cichlid", tax_id: 303518 },
  { external_reference_id: 139, name: "Pygocentrus nattereri", short_name: "Red-bellied piranha", tax_id: 42514 },
  { external_reference_id: 130, name: "Saimiri boliviensis boliviensis", short_name: "Bolivian squirrel monkey", tax_id: 39432 },
  { external_reference_id: 140, name: "Scophthalmus maximus", short_name: "Turbot", tax_id: 52904 },
  { external_reference_id: 159, name: "Seriola dumerili", short_name: "Greater amberjack", tax_id: 41447 },
  { external_reference_id: 147, name: "Stegastes partitus", short_name: "Bicolor damselfish", tax_id: 144197 },
  { external_reference_id: 269, name: "Sus scrofa usmarc", short_name: "Pig USMARC", tax_id: 9823 },
  { external_reference_id: 26, name: "Tetraodon nigroviridis", short_name: "spotted green pufferfish", tax_id: 99883 },
  { external_reference_id: 3, name: "Tursiops truncatus", short_name: "bottlenosed dolphin", tax_id: 9739 },
  { external_reference_id: 270, name: "Vombatus ursinus", short_name: "Common wombat", tax_id: 29139 },
  { external_reference_id: 23, name: "Xenopus tropicalis", short_name: "tropical clawed frog", tax_id: 8364 },
  { external_reference_id: 331, name: "Culicoides sonorensis", short_name: "Culicoides sonorensis", tax_id: 179676 },
  { external_reference_id: 41, name: "Callithrix jacchus", short_name: "white-tufted-ear marmoset", tax_id: 9483 },
  { external_reference_id: 332, name: "Danaus plexippus", short_name: "Danaus plexippus", tax_id: 13037 },
  { external_reference_id: 333, name: "Daphnia magna", short_name: "Daphnia magna", tax_id: 35525 },
  { external_reference_id: 336, name: "Dinothrombium tinctorium", short_name: "Dinothrombium tinctorium", tax_id: 1965070 },
  { external_reference_id: 245, name: "Ixodes scapularis", short_name: "Ixodes scapularis", tax_id: 6945 },
  { external_reference_id: 342, name: "Lingula anatina", short_name: "Lingula anatina", tax_id: 7574 },
  { external_reference_id: 353, name: "Onchocerca volvulus", short_name: "Onchocerca volvulus", tax_id: 6282 },
  { external_reference_id: 356, name: "Sarcoptes scabiei", short_name: "Sarcoptes scabiei", tax_id: 52283 },
  { external_reference_id: 248, name: "Arabidopsis lyrata", short_name: "Arabidopsis lyrata", tax_id: 81972 },
  { external_reference_id: 329, name: "Capitella teleta", short_name: "Capitella teleta", tax_id: 283909 },
  { external_reference_id: 48, name: "Astyanax mexicanus", short_name: "Mexican tetra", tax_id: 7994 },
  { external_reference_id: 46, name: "Bos taurus", short_name: "cattle", tax_id: 9913 },
  { external_reference_id: 61, name: "Canis familiaris", short_name: "dog", tax_id: 9615 },
  { external_reference_id: 112, name: "Carlito syrichta", short_name: "Tarsier", tax_id: 1868482 },
  { external_reference_id: 124, name: "Cebus capucinus", short_name: "Capuchin", tax_id: 1737458 },
  { external_reference_id: 44, name: "Ciona intestinalis", short_name: "vase tunicate", tax_id: 7719 },
  { external_reference_id: 66, name: "Dasypus novemcinctus", short_name: "nine-banded armadillo", tax_id: 9361 },
  { external_reference_id: 68, name: "Echinops telfairi", short_name: "small Madagascar hedgehog", tax_id: 9371 },
  { external_reference_id: 17, name: "Erinaceus europaeus", short_name: "western European hedgehog", tax_id: 9365 },
  { external_reference_id: 40, name: "Felis catus", short_name: "domestic cat", tax_id: 9685 },
  { external_reference_id: 118, name: "Fukomys damarensis", short_name: "Damara mole rat", tax_id: 885580 },
  { external_reference_id: 50, name: "Gallus gallus", short_name: "chicken", tax_id: 9031 },
  { external_reference_id: 86, name: "Haplochromis burtoni", short_name: "Burton's mouthbrooder", tax_id: 8153 },
  { external_reference_id: 53, name: "Latimeria chalumnae", short_name: "coelacanth", tax_id: 7897 },
  { external_reference_id: 36, name: "Loxodonta africana", short_name: "African savanna elephant", tax_id: 9785 },
  { external_reference_id: 82, name: "Maylandia zebra", short_name: "Zebra mbuna", tax_id: 106582 },
  { external_reference_id: 12, name: "Meleagris gallopavo", short_name: "turkey", tax_id: 9103 },
  { external_reference_id: 113, name: "Microtus ochrogaster", short_name: "Prairie vole", tax_id: 79684 },
  { external_reference_id: 67, name: "Monodelphis domestica", short_name: "gray short-tailed opossum", tax_id: 13616 },
  { external_reference_id: 145, name: "Monopterus albus", short_name: "Swamp eel", tax_id: 43700 },
  { external_reference_id: 115, name: "Mus caroli", short_name: "Ryukyu mouse", tax_id: 10089 },
  { external_reference_id: 108, name: "Mus musculus 129s1svimj", short_name: "Mouse 129S1/SvImJ", tax_id: 10090 },
  { external_reference_id: 102, name: "Mus musculus aj", short_name: "Mouse A/J", tax_id: 10090 },
  { external_reference_id: 103, name: "Mus musculus c3hhej", short_name: "Mouse C3H/HeJ", tax_id: 10090 },
  { external_reference_id: 104, name: "Mus musculus casteij", short_name: "Mouse CAST/EiJ", tax_id: 10091 },
  { external_reference_id: 109, name: "Mus musculus cbaj", short_name: "Mouse CBA/J", tax_id: 10090 },
  { external_reference_id: 110, name: "Mus musculus lpj", short_name: "Mouse LP/J", tax_id: 10090 },
  { external_reference_id: 107, name: "Mus musculus pwkphj", short_name: "Mouse PWK/PhJ", tax_id: 39442 },
  { external_reference_id: 56, name: "Mustela putorius furo", short_name: "domestic ferret", tax_id: 9669 },
  { external_reference_id: 18, name: "Oreochromis niloticus", short_name: "Nile tilapia", tax_id: 8128 },
  { external_reference_id: 27, name: "Oryctolagus cuniculus", short_name: "rabbit", tax_id: 9986 },
  { external_reference_id: 158, name: "Oryzias latipes hsok", short_name: "Japanese medaka HSOK", tax_id: 8090 },
  { external_reference_id: 51, name: "Otolemur garnettii", short_name: "small-eared galago", tax_id: 30611 },
  { external_reference_id: 63, name: "Ovis aries", short_name: "sheep", tax_id: 9940 },
  { external_reference_id: 128, name: "Pan paniscus", short_name: "Bonobo", tax_id: 9597 },
  { external_reference_id: 80, name: "Panthera tigris altaica", short_name: "Tiger", tax_id: 74533 },
  { external_reference_id: 39, name: "Petromyzon marinus", short_name: "sea lamprey", tax_id: 7757 },
  { external_reference_id: 65, name: "Pongo abelii", short_name: "Sumatran orangutan", tax_id: 9601 },
  { external_reference_id: 34, name: "Pteropus vampyrus", short_name: "large flying fox", tax_id: 132908 },
  { external_reference_id: 69, name: "Rattus norvegicus", short_name: "Norway rat", tax_id: 10116 },
  { external_reference_id: 131, name: "Rhinopithecus bieti", short_name: "Black snub-nosed monkey", tax_id: 61621 },
  { external_reference_id: 160, name: "Scleropages formosus", short_name: "Asian bonytongue", tax_id: 113540 },
  { external_reference_id: 52, name: "Sorex araneus", short_name: "European shrew", tax_id: 42254 },
  { external_reference_id: 168, name: "Sphenodon punctatus", short_name: "Tuatara", tax_id: 8508 },
  { external_reference_id: 64, name: "Taeniopygia guttata", short_name: "zebra finch", tax_id: 59729 },
  { external_reference_id: 37, name: "Tupaia belangeri", short_name: "northern tree shrew", tax_id: 37347 },
  { external_reference_id: 169, name: "Ursus americanus", short_name: "American black bear", tax_id: 9643 },
  { external_reference_id: 43, name: "Vicugna pacos", short_name: "alpaca", tax_id: 30538 },
  { external_reference_id: 47, name: "Xiphophorus maculatus", short_name: "southern platyfish", tax_id: 8083 },
  { external_reference_id: 354, name: "Orchesella cincta", short_name: "Orchesella cincta", tax_id: 48709 },
  { external_reference_id: 161, name: "Anabas testudineus", short_name: "Climbing perch", tax_id: 64144 },
  { external_reference_id: 246, name: "Pediculus humanus", short_name: "Pediculus humanus", tax_id: 121224 },
  { external_reference_id: 355, name: "Rhodnius prolixus", short_name: "Rhodnius prolixus", tax_id: 13249 },
  { external_reference_id: 421, name: "Vigna angularis", short_name: "Vigna angularis", tax_id: 3914 },
  { external_reference_id: 95, name: "Anopheles gambiae", short_name: "Anopheles gambiae", tax_id: 7165 },
  { external_reference_id: 123, name: "Chinchilla lanigera", short_name: "Long-tailed chinchilla", tax_id: 34839 },
  { external_reference_id: 146, name: "Xiphophorus couchianus", short_name: "Monterrey platyfish", tax_id: 32473 },
  { external_reference_id: 163, name: "Amphiprion percula", short_name: "Orange clownfish", tax_id: 161767 },
  { external_reference_id: 223, name: "Aspergillus niger", short_name: "Aspergillus niger", tax_id: 5061 },
  { external_reference_id: 166, name: "Canis lupus dingo", short_name: "Dingo", tax_id: 286419 },
  { external_reference_id: 8, name: "Choloepus hoffmanni", short_name: "Hoffmann's two-fingered sloth", tax_id: 9358 },
  { external_reference_id: 25, name: "Ciona savignyi", short_name: "Pacific transparent sea squirt", tax_id: 51511 },
  { external_reference_id: 117, name: "Jaculus jaculus", short_name: "Lesser Egyptian jerboa", tax_id: 51337 },
  { external_reference_id: 148, name: "Kryptolebias marmoratus", short_name: "Mangrove rivulus", tax_id: 37003 },
  { external_reference_id: 125, name: "Macaca nemestrina", short_name: "Pig-tailed macaque", tax_id: 9545 },
  { external_reference_id: 89, name: "Mandrillus leucophaeus", short_name: "Drill", tax_id: 9568 },
  { external_reference_id: 120, name: "Mesocricetus auratus", short_name: "Golden Hamster", tax_id: 10036 },
  { external_reference_id: 162, name: "Neolamprologus brichardi", short_name: "Lyretail cichlid", tax_id: 32507 },
  { external_reference_id: 121, name: "Octodon degus", short_name: "Degu", tax_id: 10160 },
  { external_reference_id: 79, name: "Oryzias melastigma", short_name: "Indian medaka", tax_id: 30732 },
  { external_reference_id: 93, name: "Paramormyrops kingsleyae", short_name: "P. kingsleyae", tax_id: 1676925 },
  { external_reference_id: 73, name: "Peromyscus maniculatus bairdii", short_name: "Northern American deer mouse", tax_id: 230844 },
  { external_reference_id: 75, name: "Poecilia latipinna", short_name: "Sailfin molly", tax_id: 48699 },
  { external_reference_id: 90, name: "Poecilia mexicana", short_name: "Shortfin molly", tax_id: 48701 },
  { external_reference_id: 151, name: "Poecilia reticulata", short_name: "Guppy", tax_id: 8081 },
  { external_reference_id: 362, name: "Strongyloides ratti", short_name: "Strongyloides ratti", tax_id: 34506 },
  { external_reference_id: 164, name: "Vulpes vulpes", short_name: "Red fox", tax_id: 9627 },
  { external_reference_id: 307, name: "Sporisorium reilianum", short_name: "Sporisorium reilianum", tax_id: 999809 },
  { external_reference_id: 33, name: "Ailuropoda melanoleuca", short_name: "giant panda", tax_id: 9646 },
  { external_reference_id: 291, name: "Leptosphaeria maculans", short_name: "Leptosphaeria maculans", tax_id: 985895 },
  { external_reference_id: 227, name: "Neurospora crassa", short_name: "Neurospora crassa", tax_id: 367110 },
  { external_reference_id: 296, name: "Phaeosphaeria nodorum", short_name: "Phaeosphaeria nodorum", tax_id: 321614 },
  { external_reference_id: 299, name: "Puccinia striiformis", short_name: "Puccinia striiformis f. sp. tritici PST-130 str. Race 130", tax_id: 875184 },
  { external_reference_id: 302, name: "Pyrenophora triticirepentis", short_name: "Pyrenophora tritici-repentis Pt-1C-BFP", tax_id: 426418 },
  { external_reference_id: 15, name: "Saccharomyces cerevisiae", short_name: "baker's yeast", tax_id: 4932 },
  { external_reference_id: 304, name: "Schizosaccharomyces japonicus", short_name: "Schizosaccharomyces japonicus", tax_id: 402676 },
  { external_reference_id: 310, name: "Tuber melanosporum", short_name: "Tuber melanosporum", tax_id: 656061 },
  { external_reference_id: 313, name: "Verticillium dahliaejr2", short_name: "Verticillium dahliae JR2", tax_id: 1202531 },
  { external_reference_id: 318, name: "Amphimedon queenslandica", short_name: "Amphimedon queenslandica", tax_id: 400682 },
  { external_reference_id: 357, name: "Schistosoma mansoni", short_name: "Schistosoma mansoni", tax_id: 6183 },
  { external_reference_id: 364, name: "Tetranychus urticae", short_name: "Tetranychus urticae", tax_id: 32264 },
  { external_reference_id: 365, name: "Thelohanellus kitauei", short_name: "Thelohanellus kitauei", tax_id: 669202 },
  { external_reference_id: 367, name: "Trichinella spiralis", short_name: "Trichinella spiralis", tax_id: 6334 },
  { external_reference_id: 369, name: "Zootermopsis nevadensis", short_name: "Zootermopsis nevadensis", tax_id: 136037 },
  { external_reference_id: 370, name: "Actinidia chinensis", short_name: "Actinidia chinensis Red5", tax_id: 1590841 },
  { external_reference_id: 372, name: "Amborella trichopoda", short_name: "Amborella trichopoda", tax_id: 13333 },
  { external_reference_id: 373, name: "Arabidopsis halleri", short_name: "Arabidopsis halleri", tax_id: 63677 },
  { external_reference_id: 374, name: "Beta vulgaris", short_name: "Beta vulgaris", tax_id: 3555 },
  { external_reference_id: 376, name: "Brassica oleracea", short_name: "Brassica oleracea", tax_id: 109376 },
  { external_reference_id: 380, name: "Corchorus capsularis", short_name: "Corchorus capsularis", tax_id: 210143 },
  { external_reference_id: 383, name: "Daucus carota", short_name: "Daucus carota", tax_id: 79200 },
  { external_reference_id: 393, name: "Marchantia polymorpha", short_name: "Marchantia polymorpha", tax_id: 3197 },
  { external_reference_id: 417, name: "Trifolium pratense", short_name: "Trifolium pratense", tax_id: 57577 },
  { external_reference_id: 418, name: "Triticum aestivum", short_name: "Triticum aestivum", tax_id: 4565 },
  { external_reference_id: 420, name: "Triticum urartu", short_name: "Triticum urartu", tax_id: 4572 },
  { external_reference_id: 429, name: "Guillardia theta", short_name: "Guillardia theta CCMP2712", tax_id: 905079 },
  { external_reference_id: 443, name: "Pythium irregulare", short_name: "Pythium irregulare", tax_id: 1223557 },
  { external_reference_id: 220, name: "Aspergillus flavus", short_name: "Aspergillus flavus NRRL3357", tax_id: 332952 },
  { external_reference_id: 167, name: "Ursus maritimus", short_name: "Polar bear", tax_id: 29073 },
  { external_reference_id: 268, name: "Lates calcarifer", short_name: "Barramundi perch", tax_id: 8187 },
  { external_reference_id: 219, name: "Aspergillus clavatus", short_name: "Aspergillus clavatus NRRL 1", tax_id: 344612 },
  { external_reference_id: 228, name: "Schizosaccharomyces pombe", short_name: "Schizosaccharomyces pombe", tax_id: 284812 },
  { external_reference_id: 322, name: "Atta cephalotes", short_name: "Atta cephalotes", tax_id: 12957 },
  { external_reference_id: 232, name: "Caenorhabditis remanei", short_name: "Caenorhabditis remanei", tax_id: 31234 },
  { external_reference_id: 335, name: "Dendroctonus ponderosae", short_name: "Dendroctonus ponderosae", tax_id: 77166 },
  { external_reference_id: 338, name: "Heliconius melpomene", short_name: "Heliconius melpomene", tax_id: 34740 },
  { external_reference_id: 340, name: "Lepeophtheirus salmonis", short_name: "Lepeophtheirus salmonis", tax_id: 72036 },
  { external_reference_id: 347, name: "Megaselia scalaris", short_name: "Megaselia scalaris", tax_id: 36166 },
  { external_reference_id: 247, name: "Pristionchus pacificus", short_name: "Pristionchus pacificus", tax_id: 54126 },
  { external_reference_id: 359, name: "Stegodyphus mimosarum", short_name: "Stegodyphus mimosarum", tax_id: 407821 },
  { external_reference_id: 360, name: "Strigamia maritima", short_name: "Strigamia maritima", tax_id: 126957 },
  { external_reference_id: 363, name: "Teleopsis dalmanni", short_name: "Teleopsis dalmanni", tax_id: 139649 },
  { external_reference_id: 371, name: "Aegilops tauschii", short_name: "Aegilops tauschii", tax_id: 200361 },
  { external_reference_id: 381, name: "Cucumis sativus", short_name: "Cucumis sativus", tax_id: 3659 },
  { external_reference_id: 382, name: "Cyanidioschyzon merolae", short_name: "Cyanidioschyzon merolae", tax_id: 280699 },
  { external_reference_id: 384, name: "Dioscorea rotundata", short_name: "Dioscorea rotundata", tax_id: 55577 },
  { external_reference_id: 388, name: "Helianthus annuus", short_name: "Helianthus annuus", tax_id: 4232 },
  { external_reference_id: 389, name: "Hordeum vulgare", short_name: "Hordeum vulgare", tax_id: 112509 },
  { external_reference_id: 390, name: "Leersia perrieri", short_name: "Leersia perrieri", tax_id: 77586 },
  { external_reference_id: 392, name: "Manihot esculenta", short_name: "Manihot esculenta", tax_id: 3983 },
  { external_reference_id: 396, name: "Nicotiana attenuata", short_name: "Nicotiana attenuata", tax_id: 49451 },
  { external_reference_id: 397, name: "Oryza barthii", short_name: "Oryza barthii", tax_id: 65489 },
  { external_reference_id: 399, name: "Oryza glaberrima", short_name: "Oryza glaberrima", tax_id: 4538 },
  { external_reference_id: 400, name: "Oryza glumipatula", short_name: "Oryza glumipatula", tax_id: 40148 },
  { external_reference_id: 401, name: "Oryza longistaminata", short_name: "Oryza longistaminata", tax_id: 4528 },
  { external_reference_id: 402, name: "Oryza meridionalis", short_name: "Oryza meridionalis", tax_id: 40149 },
  { external_reference_id: 403, name: "Oryza nivara", short_name: "Oryza nivara", tax_id: 4536 },
  { external_reference_id: 404, name: "Oryza punctata", short_name: "Oryza punctata", tax_id: 4537 },
  { external_reference_id: 405, name: "Oryza rufipogon", short_name: "Oryza rufipogon", tax_id: 4529 },
  { external_reference_id: 407, name: "Panicum hallii fil2", short_name: "Panicum hallii FIL2", tax_id: 206008 },
  { external_reference_id: 408, name: "Panicum hallii hal2", short_name: "Panicum hallii HAL2", tax_id: 1504633 },
  { external_reference_id: 412, name: "Selaginella moellendorffii", short_name: "Selaginella moellendorffii", tax_id: 88036 },
  { external_reference_id: 419, name: "Triticum dicoccoides", short_name: "Triticum dicoccoides", tax_id: 85692 },
  { external_reference_id: 422, name: "Vigna radiata", short_name: "Vigna radiata", tax_id: 3916 },
  { external_reference_id: 424, name: "Albugo laibachii", short_name: "Albugo laibachii", tax_id: 890382 },
  { external_reference_id: 425, name: "Bigelowiella natans", short_name: "Bigelowiella natans", tax_id: 753081 },
  { external_reference_id: 426, name: "Emiliania huxleyi", short_name: "Emiliania huxleyi", tax_id: 280463 },
  { external_reference_id: 430, name: "Hyaloperonospora arabidopsidis", short_name: "Hyaloperonospora arabidopsidis", tax_id: 559515 },
  { external_reference_id: 432, name: "Paramecium tetraurelia", short_name: "Paramecium tetraurelia", tax_id: 5888 },
  { external_reference_id: 434, name: "Phytophthora kernoviae", short_name: "Phytophthora kernoviae", tax_id: 1284355 },
  { external_reference_id: 435, name: "Phytophthora lateralis", short_name: "Phytophthora lateralis", tax_id: 1254522 },
  { external_reference_id: 436, name: "Phytophthora parasitica", short_name: "Phytophthora parasitica", tax_id: 1317065 },
  { external_reference_id: 437, name: "Phytophthora ramorum", short_name: "Phytophthora ramorum", tax_id: 164328 },
  { external_reference_id: 257, name: "Plasmodium falciparum", short_name: "Plasmodium falciparum 3D7", tax_id: 36329 },
  { external_reference_id: 259, name: "Plasmodium vivax", short_name: "Plasmodium vivax", tax_id: 5855 },
  { external_reference_id: 441, name: "Pythium aphanidermatum", short_name: "Pythium aphanidermatum", tax_id: 1223555 },
  { external_reference_id: 442, name: "Pythium arrhenomanes", short_name: "Pythium arrhenomanes", tax_id: 1223556 },
  { external_reference_id: 444, name: "Pythium iwayamai", short_name: "Pythium iwayamai", tax_id: 1223558 },
  { external_reference_id: 445, name: "Pythium ultimum", short_name: "Pythium ultimum", tax_id: 431595 },
  { external_reference_id: 446, name: "Pythium vexans", short_name: "Pythium vexans", tax_id: 1223560 },
  { external_reference_id: 449, name: "Trypanosoma brucei", short_name: "Trypanosoma brucei", tax_id: 5691 },
  { external_reference_id: 479, name: "Accipiter nisus", short_name: "Eurasian sparrowhawk", tax_id: 211598 },
  { external_reference_id: 271, name: "Ashbya gossypii", short_name: "Ashbya gossypii", tax_id: 284811 },
  { external_reference_id: 114, name: "Heterocephalus glaber female", short_name: "Naked mole-rat female", tax_id: 10181 },
  { external_reference_id: 222, name: "Aspergillus nidulans", short_name: "Aspergillus nidulans", tax_id: 227321 },
  { external_reference_id: 135, name: "Capra hircus", short_name: "Goat", tax_id: 9925 },
  { external_reference_id: 224, name: "Aspergillus oryzae", short_name: "Aspergillus oryzae RIB40", tax_id: 510516 },
  { external_reference_id: 275, name: "Botrytis cinerea", short_name: "Botrytis cinerea B05.10", tax_id: 332648 },
  { external_reference_id: 280, name: "Cryptococcus neoformans", short_name: "Cryptococcus neoformans var. neoformans JEC21", tax_id: 214684 },
  { external_reference_id: 292, name: "Magnaporthe oryzae", short_name: "Magnaporthe oryzae", tax_id: 242507 },
  { external_reference_id: 226, name: "Neosartorya fischeri", short_name: "Aspergillus fischeri NRRL 181", tax_id: 331117 },
  { external_reference_id: 306, name: "Sclerotinia sclerotiorum", short_name: "Sclerotinia sclerotiorum", tax_id: 665079 },
  { external_reference_id: 311, name: "Ustilago maydis", short_name: "Ustilago maydis", tax_id: 237631 },
  { external_reference_id: 316, name: "Acyrthosiphon pisum", short_name: "Acyrthosiphon pisum", tax_id: 7029 },
  { external_reference_id: 321, name: "Apis mellifera", short_name: "Apis mellifera", tax_id: 7460 },
  { external_reference_id: 326, name: "Bombyx mori", short_name: "Bombyx mori", tax_id: 7091 },
  { external_reference_id: 328, name: "Brugia malayi", short_name: "Brugia malayi", tax_id: 6279 },
  { external_reference_id: 230, name: "Caenorhabditis briggsae", short_name: "Caenorhabditis briggsae", tax_id: 6238 },
  { external_reference_id: 233, name: "Culex quinquefasciatus", short_name: "Culex quinquefasciatus", tax_id: 7176 },
  { external_reference_id: 234, name: "Drosophila ananassae", short_name: "Drosophila ananassae", tax_id: 7217 },
  { external_reference_id: 235, name: "Drosophila erecta", short_name: "Drosophila erecta", tax_id: 7220 },
  { external_reference_id: 236, name: "Drosophila grimshawi", short_name: "Drosophila grimshawi", tax_id: 7222 },
  { external_reference_id: 237, name: "Drosophila mojavensis", short_name: "Drosophila mojavensis", tax_id: 7230 },
  { external_reference_id: 238, name: "Drosophila persimilis", short_name: "Drosophila persimilis", tax_id: 7234 },
  { external_reference_id: 239, name: "Drosophila pseudoobscura", short_name: "Drosophila pseudoobscura", tax_id: 46245 },
  { external_reference_id: 240, name: "Drosophila sechellia", short_name: "Drosophila sechellia", tax_id: 7238 },
  { external_reference_id: 241, name: "Drosophila simulans", short_name: "Drosophila simulans", tax_id: 7240 },
  { external_reference_id: 242, name: "Drosophila virilis", short_name: "Drosophila virilis", tax_id: 7244 },
  { external_reference_id: 243, name: "Drosophila willistoni", short_name: "Drosophila willistoni", tax_id: 7260 },
  { external_reference_id: 244, name: "Drosophila yakuba", short_name: "Drosophila yakuba", tax_id: 7245 },
  { external_reference_id: 343, name: "Loa loa", short_name: "Loa loa", tax_id: 7209 },
  { external_reference_id: 350, name: "Nasonia vitripennis", short_name: "Nasonia vitripennis", tax_id: 7425 },
  { external_reference_id: 351, name: "Nematostella vectensis", short_name: "Nematostella vectensis", tax_id: 45351 },
  { external_reference_id: 366, name: "Tribolium castaneum", short_name: "Tribolium castaneum", tax_id: 7070 },
  { external_reference_id: 368, name: "Trichoplax adhaerens", short_name: "Trichoplax adhaerens", tax_id: 10228 },
  { external_reference_id: 250, name: "Brachypodium distachyon", short_name: "Brachypodium distachyon", tax_id: 15368 },
  { external_reference_id: 378, name: "Chlamydomonas reinhardtii", short_name: "Chlamydomonas reinhardtii", tax_id: 3055 },
  { external_reference_id: 386, name: "Glycine max", short_name: "Glycine max", tax_id: 3847 },
  { external_reference_id: 394, name: "Medicago truncatula", short_name: "Medicago truncatula", tax_id: 3880 },
  { external_reference_id: 252, name: "Oryza sativa", short_name: "Oryza sativa Japonica Group", tax_id: 39947 },
  { external_reference_id: 406, name: "Ostreococcus lucimarinus", short_name: "Ostreococcus lucimarinus", tax_id: 436017 },
  { external_reference_id: 410, name: "Physcomitrella patens", short_name: "Physcomitrella patens", tax_id: 3218 },
  { external_reference_id: 253, name: "Populus trichocarpa", short_name: "Populus trichocarpa", tax_id: 3694 },
  { external_reference_id: 413, name: "Setaria italica", short_name: "Setaria italica", tax_id: 4555 },
  { external_reference_id: 414, name: "Solanum lycopersicum", short_name: "Solanum lycopersicum", tax_id: 4081 },
  { external_reference_id: 254, name: "Sorghum bicolor", short_name: "Sorghum bicolor", tax_id: 4558 },
  { external_reference_id: 255, name: "Vitis vinifera", short_name: "Vitis vinifera", tax_id: 29760 },
  { external_reference_id: 423, name: "Zea mays", short_name: "Zea mays", tax_id: 4577 },
  { external_reference_id: 208, name: "Dictyostelium discoideum", short_name: "Dictyostelium discoideum", tax_id: 352472 },
  { external_reference_id: 427, name: "Entamoeba histolytica", short_name: "Entamoeba histolytica", tax_id: 294381 },
  { external_reference_id: 428, name: "Giardia lamblia", short_name: "Giardia lamblia", tax_id: 184922 },
  { external_reference_id: 431, name: "Leishmania major", short_name: "Leishmania major", tax_id: 347515 },
  { external_reference_id: 256, name: "Phaeodactylum tricornutum", short_name: "Phaeodactylum tricornutum", tax_id: 556484 },
  { external_reference_id: 433, name: "Phytophthora infestans", short_name: "Phytophthora infestans", tax_id: 403677 },
  { external_reference_id: 447, name: "Tetrahymena thermophila", short_name: "Tetrahymena thermophila", tax_id: 312017 },
  { external_reference_id: 260, name: "Thalassiosira pseudonana", short_name: "Thalassiosira pseudonana", tax_id: 296543 },
  { external_reference_id: 221, name: "Aspergillus fumigatus", short_name: "Aspergillus fumigatus Af293", tax_id: 330879 },
  { external_reference_id: 469, name: "Sus scrofa berkshire", short_name: "Pig - Berkshire", tax_id: 9823 },
  { external_reference_id: 132, name: "Aotus nancymaae", short_name: "Ma's night monkey", tax_id: 37293 },
  { external_reference_id: 85, name: "Chrysemys picta bellii", short_name: "Painted turtle", tax_id: 8478 },
  { external_reference_id: 463, name: "Denticeps clupeoides", short_name: "Denticle herring", tax_id: 299321 },
  { external_reference_id: 87, name: "Nannospalax galili", short_name: "Upper Galilee mountains blind mole rat", tax_id: 1026970 },
  { external_reference_id: 470, name: "Sus scrofa hampshire", short_name: "Pig - Hampshire", tax_id: 9823 },
  { external_reference_id: 137, name: "Acanthochromis polyacanthus", short_name: "Spiny chromis", tax_id: 80966 },
  { external_reference_id: 149, name: "Amphilophus citrinellus", short_name: "Midas cichlid", tax_id: 61819 },
  { external_reference_id: 156, name: "Amphiprion ocellaris", short_name: "Clown anemonefish", tax_id: 80972 },
  { external_reference_id: 5, name: "Anolis carolinensis", short_name: "green anole", tax_id: 28377 },
  { external_reference_id: 144, name: "Astatotilapia calliptera", short_name: "Eastern happy", tax_id: 8154 },
  { external_reference_id: 460, name: "Betta splendens", short_name: "Siamese fighting fish", tax_id: 158456 },
  { external_reference_id: 461, name: "Clupea harengus", short_name: "Atlantic herring", tax_id: 7950 },
  { external_reference_id: 263, name: "Bos indicus hybrid", short_name: "Hybrid - Bos Indicus", tax_id: 30522 },
  { external_reference_id: 265, name: "Callorhinchus milii", short_name: "Elephant shark", tax_id: 7868 },
  { external_reference_id: 465, name: "Gouania willdenowi", short_name: "Blunt-snouted clingfish", tax_id: 441366 },
  { external_reference_id: 91, name: "Cricetulus griseus crigri", short_name: "Chinese hamster CriGri", tax_id: 10029 },
  { external_reference_id: 466, name: "Larimichthys crocea", short_name: "Large yellow croaker", tax_id: 215358 },
  { external_reference_id: 294, name: "Melampsora laricipopulina", short_name: "Melampsora larici-populina", tax_id: 747676 },
  { external_reference_id: 467, name: "Parambassis ranga", short_name: "Indian glassy fish", tax_id: 210632 },
  { external_reference_id: 38, name: "Gasterosteus aculeatus", short_name: "three-spined stickleback", tax_id: 69293 },
  { external_reference_id: 472, name: "Sus scrofa landrace", short_name: "Pig - Landrace", tax_id: 9823 },
  { external_reference_id: 62, name: "Ictidomys tridecemlineatus", short_name: "thirteen-lined ground squirrel", tax_id: 43179 },
  { external_reference_id: 473, name: "Sus scrofa largewhite", short_name: "Pig - Largewhite", tax_id: 9823 },
  { external_reference_id: 129, name: "Macaca fascicularis", short_name: "Crab-eating macaque", tax_id: 9541 },
  { external_reference_id: 30, name: "Pelodiscus sinensis", short_name: "Chinese soft-shelled turtle", tax_id: 13735 },
  { external_reference_id: 88, name: "Periophthalmus magnuspinnatus", short_name: "P. magnuspinnatus", tax_id: 409849 },
  { external_reference_id: 127, name: "Rhinopithecus roxellana", short_name: "Golden snub-nosed monkey", tax_id: 61622 },
  { external_reference_id: 475, name: "Sus scrofa pietrain", short_name: "Pig - Pietrain", tax_id: 9823 },
  { external_reference_id: 476, name: "Sus scrofa rongchang", short_name: "Pig - Rongchang", tax_id: 9823 },
  { external_reference_id: 478, name: "Sus scrofa wuzhishan", short_name: "Pig - Wuzhishan", tax_id: 9823 },
  { external_reference_id: 330, name: "Crassostrea gigas", short_name: "Crassostrea gigas", tax_id: 29159 },
  { external_reference_id: 344, name: "Lottia gigantea", short_name: "Lottia gigantea", tax_id: 225164 },
  { external_reference_id: 312, name: "Verticillium dahliae", short_name: "Verticillium dahliae", tax_id: 498257 },
  { external_reference_id: 325, name: "Bombus terrestris", short_name: "Bombus terrestris", tax_id: 30195 },
  { external_reference_id: 94, name: "Aedes aegypti", short_name: "Aedes aegypti", tax_id: 7159 },
  { external_reference_id: 334, name: "Daphnia pulex", short_name: "Daphnia pulex", tax_id: 6669 },
  { external_reference_id: 339, name: "Helobdella robusta", short_name: "Helobdella robusta", tax_id: 6412 },
  { external_reference_id: 358, name: "Solenopsis invicta", short_name: "Solenopsis invicta", tax_id: 13686 },
  { external_reference_id: 375, name: "Brassica napus", short_name: "Brassica napus", tax_id: 3708 },
  { external_reference_id: 377, name: "Brassica rapa", short_name: "Brassica rapa", tax_id: 3711 },
  { external_reference_id: 379, name: "Chondrus crispus", short_name: "Chondrus crispus", tax_id: 2769 },
  { external_reference_id: 385, name: "Galdieria sulphuraria", short_name: "Galdieria sulphuraria", tax_id: 130081 },
  { external_reference_id: 387, name: "Gossypium raimondii", short_name: "Gossypium raimondii", tax_id: 29730 },
  { external_reference_id: 391, name: "Lupinus angustifolius", short_name: "Lupinus angustifolius", tax_id: 3871 },
  { external_reference_id: 395, name: "Musa acuminata", short_name: "Musa acuminata", tax_id: 214687 },
  { external_reference_id: 398, name: "Oryza brachyantha", short_name: "Oryza brachyantha", tax_id: 4533 },
  { external_reference_id: 409, name: "Phaseolus vulgaris", short_name: "Phaseolus vulgaris", tax_id: 3885 },
  { external_reference_id: 411, name: "Prunus persica", short_name: "Prunus persica", tax_id: 3760 },
  { external_reference_id: 415, name: "Solanum tuberosum", short_name: "Solanum tuberosum", tax_id: 4113 },
  { external_reference_id: 416, name: "Theobroma cacao", short_name: "Theobroma cacao", tax_id: 3641 },
  { external_reference_id: 438, name: "Phytophthora sojae", short_name: "Phytophthora sojae", tax_id: 67593 },
  { external_reference_id: 459, name: "Astyanax mexicanus pachon", short_name: "Pachon cavefish", tax_id: 7994 },
  { external_reference_id: 286, name: "Fusarium pseudograminearum", short_name: "Fusarium pseudograminearum", tax_id: 1028729 },
  { external_reference_id: 179, name: "Anas platyrhynchos platyrhynchos", short_name: "Duck", tax_id: 8840 },
  { external_reference_id: 264, name: "Bos taurus hybrid", short_name: "Hybrid - Bos Taurus", tax_id: 30522 },
  { external_reference_id: 303, name: "Schizosaccharomyces cryophilus", short_name: "Schizosaccharomyces cryophilus", tax_id: 653667 },
  { external_reference_id: 361, name: "Strongylocentrotus purpuratus", short_name: "Strongylocentrotus purpuratus", tax_id: 7668 },
  { external_reference_id: 249, name: "Arabidopsis thaliana", short_name: "Arabidopsis thaliana", tax_id: 3702 },
  { external_reference_id: 521, name: "Coffea canephora", short_name: "Coffea canephora", tax_id: 49390 },
  { external_reference_id: 522, name: "Cynara cardunculus", short_name: "Cynara cardunculus", tax_id: 59895 },
  { external_reference_id: 524, name: "Triticum turgidum", short_name: "Triticum turgidum", tax_id: 4567 },
  { external_reference_id: 480, name: "Amazona collaria", short_name: "Yellow-billed parrot", tax_id: 241587 },
  { external_reference_id: 481, name: "Anser cygnoides", short_name: "Swan goose", tax_id: 8845 },
  { external_reference_id: 482, name: "Aquila chrysaetos chrysaetos", short_name: "Golden eagle", tax_id: 223781 },
  { external_reference_id: 448, name: "Toxoplasma gondii", short_name: "Toxoplasma gondii ME49", tax_id: 508771 },
  { external_reference_id: 526, name: "Aedes aegypti lvpagwg", short_name: "Aedes aegypti (LVP_AGWG)", tax_id: 7159 },
  { external_reference_id: 528, name: "Anopheles albimanus", short_name: "Anopheles albimanus", tax_id: 7167 },
  { external_reference_id: 529, name: "Anopheles arabiensis", short_name: "Anopheles arabiensis", tax_id: 7173 },
  { external_reference_id: 531, name: "Anopheles coluzzii", short_name: "Anopheles coluzzii", tax_id: 1518534 },
  { external_reference_id: 533, name: "Anopheles culicifacies", short_name: "Anopheles culicifacies", tax_id: 139723 },
  { external_reference_id: 534, name: "Anopheles dirus", short_name: "Anopheles dirus", tax_id: 7168 },
  { external_reference_id: 535, name: "Anopheles epiroticus", short_name: "Anopheles epiroticus", tax_id: 199890 },
  { external_reference_id: 537, name: "Anopheles funestus", short_name: "Anopheles funestus", tax_id: 62324 },
  { external_reference_id: 538, name: "Anopheles maculatus", short_name: "Anopheles maculatus", tax_id: 74869 },
  { external_reference_id: 539, name: "Anopheles melas", short_name: "Anopheles melas", tax_id: 34690 },
  { external_reference_id: 541, name: "Anopheles minimus", short_name: "Anopheles minimus", tax_id: 112268 },
  { external_reference_id: 544, name: "Anopheles sinensis", short_name: "Anopheles sinensis", tax_id: 74873 },
  { external_reference_id: 543, name: "Anopheles sinensis china", short_name: "Anopheles sinensis (China)", tax_id: 74873 },
  { external_reference_id: 546, name: "Anopheles stephensi indian", short_name: "Anopheles stephensi (Indian)", tax_id: 30069 },
  { external_reference_id: 548, name: "Cimex lectularius", short_name: "Cimex lectularius", tax_id: 79782 },
  { external_reference_id: 549, name: "Glossina austeni", short_name: "Glossina austeni", tax_id: 7395 },
  { external_reference_id: 551, name: "Glossina fuscipes", short_name: "Glossina fuscipes fuscipes", tax_id: 201502 },
  { external_reference_id: 552, name: "Glossina morsitans", short_name: "Glossina morsitans", tax_id: 37546 },
  { external_reference_id: 554, name: "Glossina palpalis", short_name: "Glossina palpalis", tax_id: 67801 },
  { external_reference_id: 519, name: "Hofstenia miamia", short_name: "Hofstenia miamia", tax_id: 442651 },
  { external_reference_id: 484, name: "Bos grunniens", short_name: "Domestic yak", tax_id: 30521 },
  { external_reference_id: 485, name: "Camelus dromedarius", short_name: "Arabian camel", tax_id: 9838 },
  { external_reference_id: 487, name: "Canis lupus familiarisgreatdane", short_name: "Dog - Great Dane", tax_id: 9615 },
  { external_reference_id: 488, name: "Catagonus wagneri", short_name: "Chacoan peccary", tax_id: 51154 },
  { external_reference_id: 490, name: "Cyprinus carpio germanmirror", short_name: "Common carp german mirror", tax_id: 7962 },
  { external_reference_id: 492, name: "Cyprinus carpio huanghe", short_name: "Common carp huanghe", tax_id: 7962 },
  { external_reference_id: 493, name: "Echeneis naucrates", short_name: "Live sharksucker", tax_id: 173247 },
  { external_reference_id: 495, name: "Lynx canadensis", short_name: "Canada lynx", tax_id: 61383 },
  { external_reference_id: 496, name: "Moschus moschiferus", short_name: "Siberian musk deer", tax_id: 68415 },
  { external_reference_id: 498, name: "Neogobius melanostomus", short_name: "Round goby", tax_id: 47308 },
  { external_reference_id: 499, name: "Oreochromis aureus", short_name: "Blue tilapia", tax_id: 47969 },
  { external_reference_id: 500, name: "Pavo cristatus", short_name: "Indian peafowl", tax_id: 9049 },
  { external_reference_id: 502, name: "Physeter catodon", short_name: "Sperm whale", tax_id: 9755 },
  { external_reference_id: 503, name: "Podarcis muralis", short_name: "Common wall lizard", tax_id: 64176 },
  { external_reference_id: 505, name: "Rhinolophus ferrumequinum", short_name: "Greater horseshoe bat", tax_id: 59479 },
  { external_reference_id: 506, name: "Salarias fasciatus", short_name: "Jewelled blenny", tax_id: 181472 },
  { external_reference_id: 508, name: "Salmo trutta", short_name: "River trout", tax_id: 8032 },
  { external_reference_id: 510, name: "Sinocyclocheilus grahami", short_name: "Golden-line barbel", tax_id: 75366 },
  { external_reference_id: 511, name: "Sinocyclocheilus rhinocerous", short_name: "Horned golden-line barbel", tax_id: 307959 },
  { external_reference_id: 513, name: "Sphaeramia orbicularis", short_name: "Orbiculate cardinalfish", tax_id: 375764 },
  { external_reference_id: 514, name: "Strigops habroptila", short_name: "Kakapo", tax_id: 2489341 },
  { external_reference_id: 516, name: "Suricata suricatta", short_name: "Meerkat", tax_id: 37032 },
  { external_reference_id: 517, name: "Terrapene carolina triunguis", short_name: "Three-toed box turtle", tax_id: 2587831 },
  { external_reference_id: 520, name: "Capsicum annuum", short_name: "Capsicum annuum", tax_id: 4072 },
  { external_reference_id: 352, name: "Octopus bimaculoides", short_name: "Octopus bimaculoides", tax_id: 37653 },
  { external_reference_id: 527, name: "Aedes albopictus", short_name: "Aedes albopictus", tax_id: 7160 },
  { external_reference_id: 530, name: "Anopheles atroparvus", short_name: "Anopheles atroparvus", tax_id: 41427 },
  { external_reference_id: 532, name: "Anopheles coluzzii ngousso", short_name: "Anopheles coluzzii (Ngousso)", tax_id: 1518534 },
  { external_reference_id: 536, name: "Anopheles farauti", short_name: "Anopheles farauti", tax_id: 69004 },
  { external_reference_id: 540, name: "Anopheles merus", short_name: "Anopheles merus", tax_id: 30066 },
  { external_reference_id: 542, name: "Anopheles quadriannulatus", short_name: "Anopheles quadriannulatus", tax_id: 34691 },
  { external_reference_id: 545, name: "Anopheles stephensi", short_name: "Anopheles stephensi", tax_id: 30069 },
  { external_reference_id: 547, name: "Biomphalaria glabrata", short_name: "Biomphalaria glabrata", tax_id: 6526 },
  { external_reference_id: 550, name: "Glossina brevipalpis", short_name: "Glossina brevipalpis", tax_id: 37001 },
  { external_reference_id: 553, name: "Glossina pallidipes", short_name: "Glossina pallidipes", tax_id: 7398 },
  { external_reference_id: 555, name: "Ixodes scapularis ise6", short_name: "Ixodes scapularis (ISE6)", tax_id: 6945 },
  { external_reference_id: 556, name: "Lutzomyia longipalpis", short_name: "Lutzomyia longipalpis", tax_id: 7200 },
  { external_reference_id: 558, name: "Phlebotomus papatasi", short_name: "Phlebotomus papatasi", tax_id: 29031 },
  { external_reference_id: 559, name: "Stomoxys calcitrans", short_name: "Stomoxys calcitrans", tax_id: 35570 },
  { external_reference_id: 560, name: "Citrus clementina", short_name: "Citrus clementina", tax_id: 85681 },
  { external_reference_id: 523, name: "Eragrostis tef", short_name: "Eragrostis tef", tax_id: 110835 },
  { external_reference_id: 561, name: "Ipomoea triloba", short_name: "Ipomoea triloba", tax_id: 35885 },
  { external_reference_id: 562, name: "Prunus avium", short_name: "Prunus avium", tax_id: 42229 },
  { external_reference_id: 563, name: "Saccharum spontaneum", short_name: "Saccharum spontaneum", tax_id: 62335 },
  { external_reference_id: 525, name: "Pseudonitzschia multistriata", short_name: "Pseudo-nitzschia multistriata", tax_id: 183589 },
  { external_reference_id: 483, name: "Athene cunicularia", short_name: "Burrowing owl", tax_id: 194338 },
  { external_reference_id: 486, name: "Canis lupus familiarisbasenji", short_name: "Dog - Basenji", tax_id: 9615 },
  { external_reference_id: 489, name: "Chrysolophus pictus", short_name: "Golden pheasant", tax_id: 9089 },
  { external_reference_id: 462, name: "Cottoperca gobio", short_name: "Channel bull blenny", tax_id: 56716 },
  { external_reference_id: 491, name: "Cyprinus carpio hebaored", short_name: "Common carp hebao red", tax_id: 7962 },
  { external_reference_id: 464, name: "Erpetoichthys calabaricus", short_name: "Reedfish", tax_id: 27687 },
  { external_reference_id: 494, name: "Erythrura gouldiae", short_name: "Gouldian finch", tax_id: 44316 },
  { external_reference_id: 497, name: "Myripristis murdjan", short_name: "Pinecone soldierfish", tax_id: 586833 },
  { external_reference_id: 501, name: "Phasianus colchicus", short_name: "Ring-necked pheasant", tax_id: 9054 },
  { external_reference_id: 504, name: "Pseudonaja textilis", short_name: "Eastern brown snake", tax_id: 8673 },
  { external_reference_id: 509, name: "Sinocyclocheilus anshuiensis", short_name: "Blind barbel", tax_id: 1608454 },
  { external_reference_id: 512, name: "Sparus aurata", short_name: "Gilthead seabream", tax_id: 8175 },
  { external_reference_id: 515, name: "Struthio camelus australis", short_name: "African ostrich", tax_id: 441894 },
  { external_reference_id: 468, name: "Sus scrofa bamei", short_name: "Pig - Bamei", tax_id: 9823 },
  { external_reference_id: 471, name: "Sus scrofa jinhua", short_name: "Pig - Jinhua", tax_id: 9823 },
  { external_reference_id: 474, name: "Sus scrofa meishan", short_name: "Pig - Meishan", tax_id: 9823 },
  { external_reference_id: 477, name: "Sus scrofa tibetan", short_name: "Pig - Tibetan", tax_id: 9823 },
  { external_reference_id: 518, name: "Varanus komodoensis", short_name: "Komodo dragon", tax_id: 61221 },
  { external_reference_id: 557, name: "Musca domestica", short_name: "Musca domestica", tax_id: 7370 },
  { external_reference_id: 507, name: "Salmo salar", short_name: "Atlantic salmon", tax_id: 8030 },
  { external_reference_id: 35, name: "Drosophila melanogaster", short_name: "fruit fly", tax_id: 7227 },
  { external_reference_id: 22, name: "Caenorhabditis elegans", short_name: "Caenorhabditis elegans", tax_id: 6239 }
])
