default: &default
  adapter: postgresql
  timeout: 5000
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "no_password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: scfair_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: scfair_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "scfair_production" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
