source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "8.0.0.rc1"

gem "propshaft", "~> 1.1"

gem "pg", "~> 1.5"

gem "puma", "~> 6.4"

gem "importmap-rails", "~> 2.0"

gem "turbo-rails", "~> 2.0"

gem "stimulus-rails", "~> 1.3"

gem "bootsnap", "~> 1.18", require: false

gem "thruster", "~> 0.1.8", require: false

gem "sunspot_rails", "~> 2.7"
gem "sunspot_solr", "~> 2.7"

gem "httparty", "~> 0.22.0"

gem "progress_bar", "~> 1.3"
gem "will_paginate", "~> 4.0"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "dotenv"
  gem "rspec-rails", "~> 7.0.1"
  gem "factory_bot_rails", "~> 6.4.3"
  gem "database_cleaner-active_record", "~> 2.2.0"
  gem "pry", "~> 0.14.2"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

gem "devise", "~> 4.9"
